name: Release

on:
  push:
    tags:
      - 'v.[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: { java-version: 17 }
      - name: Build release APK and AAB after test
        run: |
          ./gradlew testReleaseUnitTest assembleRelease bundleRelease publishReleaseBundle
        env:
          NUMBERS_RELEASE_JKS: ${{ secrets.NUMBERS_RELEASE_JKS }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            androidApp/build/outputs/apk/release/androidApp-release.apk
            androidApp/build/outputs/bundle/release/androidApp-release.aab
